triggers:
  - name: trigger01
    type: trigger
    version:
      counter: 4
    flags: f1
    
  - name: trigger02
    type: trigger
    version:
      counter: 4
    flags: f1
    
  - name: trigger03
    type: trigger
    version:
      counter: 6
  - name: trigger04
    type: trigger
    version:
      counter: 54
      
  - name: trigger05
    type: trigger
    version:
      counter: 63
       
    
 
 #   type: trigger
 #   version:
   #   counter: 0
   # flags: t2
