triggers:
  - name: trigger01
    type: trigger
    version:
      counter: 4
    flags: f1
    
  - name: trigger02
    type: trigger
    version:
      counter: 3
    flags: f1
    
  - name: trigger03
    type: trigger
    version:
      counter: 6
    
 #   type: trigger
 #   version:
   #   counter: 0
   # flags: t2
