jobs:
  - name: sample-runsh-jf-new
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-testjf-new
        showBuildStatus: true
      - IN: trigger-jf-new
      - IN: test-cli-jfrog-new
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-testjf-new/gitRepo/echo.sh 
        - script: sudo jfrog rt u IN/sample-testjf-new/gitRepo/testgeneric.sh test-jfrog-ship
        - script: sudo jfrog rt dl test-jfrog-ship/echo.sh
    flags: bar
    
    
  - name: manifest-jfrog
    type: manifest
    steps:
      - IN: test-jfrogfiles-new
    flags: foo
      
  - name: manifest-deepika
    type: manifest
    steps:
      - IN: deepika-image
      
  - name: deploy-test-newnode
    type: deploy
    steps:
      - IN: manifest-jfrog
        force: true
      - IN: test_newnode_cluster
 
  - name: deploy-deepika
    type: deploy
    steps:
      - IN: manifest-jfrog
        force: true
      - IN: test-deepika-nc
 
  - name: deploy-jfrog
    type: deploy
    steps:
      - IN: manifest-jfrog
        force: true
      - IN: test_node_cluster
      - TASK:
        - script: sudo jfrog rt dl test-jfrog-ship/testgeneric.sh
       # - script: sudo rm -rf /opt/tomcat/webapps/HelloWorld.war
    flags: foo
 
     
  
  
        
  
