jobs:
  - name: sample-runsh-docker
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-docker
        showBuildStatus: true
      - IN: test-cli-docker-new
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: 'cd /build/IN/sample-script-pus/gitRepo'
        - script: 'docker pull shippabledocker/sample_node_pvt'
        - script: 'docker build -t=shippabledocker/hitchcock3_sample_node:runshnew  .'
        - script: 'docker push shippabledocker/hitchcock3_sample_node:runshnew'
   # flags: far
 
 
