triggers:
  - name: trigger01
    type: trigger
    version:
      counter: 2
    flags: f1
    
  - name: trigger02
    type: trigger
    version:
      counter: 3
    flags: f1
    
  - name: trigger03
    type: trigger
    version:
      counter: 5
    
 #   type: trigger
 #   version:
   #   counter: 0
   # flags: t2
