jobs:
  
    
  - name: manifest-d
    type: manifest
    steps:
      - IN: sample_img_jf-new-d
    flags: foo
      
  - name: deploy-d
    type: deploy
    steps:
      - IN: manifest-d
        force: true
      - IN: deepikanc
      - TASK:
        - script: echo "hello"
        #- script: sudo jfrog rt dl test-jfrog-ship/testgeneric.sh
       # - script: sudo rm -rf /opt/tomcat/webapps/HelloWorld.war
    flags: foo
 
     
  
  
        
  
