jobs:
  - name: sample-runsh
    type: runSh
    steps:
      - IN: sample-script-01
      - IN: triggertest1
      - IN: test-trigger
      - TASK:
        - script: IN/sample-script-01/gitrepo/echo.sh
