jobs:
  - name: sample-runsh-dockerRegistry
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-dockerRegistry
        showBuildStatus: true
      - IN: test-cli-dockerRegistry
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: 'cd /build/IN/sample-test-script-dockerRegistry/gitRepo'
        - script: 'docker pull quay.io/revathird/samplenode_test'
        - script: 'docker build -t=quay.io/revathird/samplenode_test:dri  .'
        - script: 'docker push quay.io/revathird/samplenode_test:dri'
   # flags: far
 
  - name: sample-runsh-dockerRegistry-integration
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-dockerRegistry
        showBuildStatus: true
      - IN: test-int-dockerRegistry
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: echo $TESTINTDOCKERREGISTRY_INTEGRATION_USERNAME
        - script: echo $TESTINTDOCKERREGISTRY_INTEGRATION_PASSWORD
        - script: echo $TESTINTDOCKERREGISTRY_INTEGRATION_EMAIL
        - script: echo $TESTINTDOCKERREGISTRY_INTEGRATION_URL
 
  - name: sample-runsh-docker-image
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-test-script-docker
        showBuildStatus: true
      - IN: sample_img_dockerRegistry
      
     
      - TASK:
        - script: echo $SAMPLE_IMG_DOCKERREGISTRY_INTEGRATION_USERNAME
        - script: echo $SAMPLE_IMG_DOCKERREGISTRY_INTEGRATION_PASSWORD
        - script: echo $SAMPLE_IMG_DOCKERREGISTRY_INTEGRATION_EMAIL
        - script: echo $SAMPLE_IMG_DOCKERREGISTRY_INTEGRATION_URL
        
        
  - name: manifest_dockerRegistry
    type: manifest
    steps:
      - IN: sample_img_dockerRegistry
      
      
  - name: dockerRegistry_deploy
    type: deploy
    steps:
      - IN: manifest_dockerRegistry
      - IN: ddc_cluster-1
      - IN: ddc_dopts-1
      - TASK: managed
      #- IN: env-tripub
