jobs:
  - name: sample-runsh018
    type: runSh
   # allowPublicAccess: true
    steps:
      - IN: sample-script-012
      - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
    flags: job1
    
  - name: runcliscript
    type: runCLI
    #allowPublicAccess: true
    steps:      
      - IN: sample-script-012 
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
