triggers:
  - name: trigger01
    type: trigger
    version:
      counter: 4
    flags: f1
    
  - name: trigger02
    type: trigger
    version:
      counter: 4
    flags: f1
    
  - name: trigger03
    type: trigger
    version:
      counter: 7
  - name: trigger04
    type: trigger
    version:
      counter: 502
      
  - name: trigger05
    type: trigger
    version:
      counter: 79
       
    
 
 #   type: trigger
 #   version:
   #   counter: 0
   # flags: t2
