jobs:
  - name: sample-runsh-jf
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-testjf
        showBuildStatus: true
      - IN: trigger-jf
      - IN: test-cli-jfrog
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-testjf/gitRepo/echo.sh  
        - script: sudo jfrog rt u IN/sample-testjf/gitRepo/echo.sh test-jfrog-ship
        - script: sudo jfrog rt dl test-jfrog-ship/echo.sh
    flags: test-very-long-flagname-shows-in-the-subscription-and-custom-dashboard-tooltip-test-16
 
  - name: manifest-jfrog-old
    type: manifest
    steps:
      - IN: test-jfrogfiles
      
  - name: deploy-jfrog-old
    type: deploy
    steps:
      - IN: manifest-jfrog-pld
        force: true
      - IN: test_node_cluster-oldjf
     #- TASK:
       # - script: sudo jfrog rt dl test-jfrog-ship/testoct.sh
  
  
        
  
