jobs:
  - name: sample-runsh01
    #type: runSh
    steps:
      - IN: sample-script-012
      - IN: trigger01
      - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
    flags: job1
