jobs:
  - name: sample-runsh-jf
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: ssample-testjf
        showBuildStatus: true
      - IN: trigger01
      - IN: test-cli-jfrog
      #- IN: test-jfrogfile
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh  
        - script: sudo jfrog rt u IN/sample-script-012/gitRepo/echo.sh test-jfrog-ship
    flags: test-very-long-flagname-shows-in-the-subscription-and-custom-dashboard-tooltip-test-16
 
     
  
  
        
  
