jobs:
  - name: sample-runsh018
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-script-012
        showBuildStatus: true
      - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
    flags: job1
  - name: release-dev
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-script-012
      - IN: sample-runsh018
      - IN: runcliscript
      - IN: sample-runsh017
      - IN: trigger02
        showBuildStatus: true
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh  
  - name: runcliscript
    type: runCLI
    allowPublicAccess: false
    steps:      
      - IN: sample-script-012 
      - IN: trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
  - name: sample-runsh017
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-script-012
        showBuildStatus: true
      - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-script-012/gitRepo/echo.sh
