jobs:
  - name: sample-runsh
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - IN: test-trigger
      - TASK:
        - script: IN/sample-script/sample-script-3/echo.sh
